Repository AY2324S1-CS2103T-T08-3/tp, pull requests merged in 2023-11, with the labels that each got.

#158 Implement sortT command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/SortTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/testutil/ModelStubWithProjectAndEmployee.java
Labels: priority.Medium

#163 Fix markT, unmarkT and deleteT bugs
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkTaskCommandParser.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkTaskCommandParserTest.java
Labels: priority.Medium

#165 Make project name its own class / Change name prefix for addP
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddProjectCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/AssignProjectCommand.java
  src/main/java/seedu/address/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkProjectCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/PriorityProjectCommand.java
  src/main/java/seedu/address/logic/commands/ProjectDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/UnassignProjectCommand.java
  src/main/java/seedu/address/logic/commands/UnassignTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkProjectCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/model/project/Name.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/test/java/seedu/address/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/PriorityProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
Labels: priority.Medium, type.Task

#168 Update addT to allow immediate assigning of a task to an employee
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/ModelStubWithEmptyProjectListAndEmptyEmployeeList.java
Labels: priority.Medium, type.Task

#170 Fix bug where assigned employee is not edited during various commands
  src/main/java/seedu/address/logic/commands/DeleteEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/EditEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/UnassignProjectCommand.java
Labels: type.Bug

#174 Enhance project priority and deadline commands
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeadlineProjectCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/EditProjectCommand.java
  src/main/java/seedu/address/logic/commands/MarkProjectCommand.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/PriorityProjectCommand.java
  src/main/java/seedu/address/logic/commands/ProjectDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/UnassignProjectCommand.java
  src/main/java/seedu/address/logic/commands/UnassignTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkProjectCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeadlineProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/EditProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PriorityProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/main/java/seedu/address/model/project/Deadline.java
  src/main/java/seedu/address/model/project/Priority.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/test/java/seedu/address/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeadlineProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/PriorityProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/DeadlineProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PriorityProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/model/project/PriorityTest.java
  src/test/java/seedu/address/model/project/ProjectPriorityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/testutil/EditProjectDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
Labels: priority.High

#177 Add sample data for projects and tasks
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#179 Add sample data for tasks and projects
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#181 Update UG
  docs/UserGuide.md
  docs/images/HelpWindow.png
  docs/images/HelpWindowUgLink.png
  docs/images/ListE.png
  docs/images/Ui.png
  docs/images/circledHelpGUI.png
  docs/images/circledHelpGui.png
  docs/images/findE.png
  docs/images/findP.png
  docs/images/helpMessage.png
  docs/images/listP.png
  docs/images/liste.png
  docs/images/listp.png
Labels: priority.High

#184 Update User Guide for v1.3
  docs/UserGuide.md
  docs/images/HelpWindow.png
  docs/images/HelpWindowUgLink.png
  docs/images/listE.png
Labels: priority.High

#186 Fix UG Bugs
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
Labels: priority.High

#189 Amend FXML file name
  src/main/java/seedu/address/ui/TaskListPanel.java
Labels: priority.High, type.Bug, severity.High

#191 Fix deadline examples in ug
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#192 Fix missing and wrong examples in UG
  docs/UserGuide.md
Labels: type.Bug, severity.Low

#226 Fix storage branch
  src/main/java/seedu/address/model/TaskHub.java
  src/main/java/seedu/address/model/employee/UniqueEmployeeList.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonSerializableTaskHub.java
  src/test/java/seedu/address/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindProjectCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/TaskHubTest.java
  src/test/java/seedu/address/model/project/UniqueProjectListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/storage/JsonTaskHubStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High

#237 Update PPP - Chandan
  docs/team/chandan8186.md
Labels: type.Documentation

#240 Reformat UG
  docs/UserGuide.md
  docs/images/UiParts.png
Labels: type.Documentation

#243 Add UG Introduction
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#241 Update DG with Proposed Features
  docs/DeveloperGuide.md
  docs/diagrams/PriorityPSequenceDiagram.puml
  docs/images/PriorityPSequenceDiagram.png
Labels: type.Documentation

#227 Update DG and improve code quality, remove dead Task code
  docs/DeveloperGuide.md
  docs/diagrams/AddTSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EmployeeClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ProjectClassDiagram.puml
  docs/diagrams/TaskClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddTSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EmployeeClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ProjectClassDiagram.png
  docs/images/TaskClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskHub.java
  src/main/java/seedu/address/model/TaskHub.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/TaskHubTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/ModelStubWithEmptyProjectList.java
  src/test/java/seedu/address/testutil/ModelStubWithEmptyProjectListAndEmptyEmployeeList.java
  src/test/java/seedu/address/testutil/ModelStubWithProjectAndEmployee.java
Labels: type.Documentation

#224 Fix addT bug - illegal employee bug and error messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/ModelStubWithEmptyProjectListAndEmptyEmployeeList.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#246 Update Model Component in DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/EmployeeClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ProjectClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/EmployeeClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ProjectClassDiagram.png
Labels: priority.High, type.Documentation

#230 Improve testing for markT, unmarkT, find, list and sort commands
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/SortTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/FindEmployeeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkTaskCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/employee/EmployeeNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/employee/EmployeeUnderFilteredProjectsPredicateTest.java
  src/test/java/seedu/address/model/project/ProjectDoneByFilteredEmployeesPredicateTest.java
  src/test/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: priority.Medium

#259 Update Data Storage section in UG
  docs/UserGuide.md
Labels: type.Documentation

#262 Update Effort section of DG
  docs/DeveloperGuide.md
  docs/team/chandan8186.md
Labels: type.Documentation
