Repository AY2324S1-CS2103T-T08-3/tp, pull requests merged in 2023-10, with the labels that each got.

#69 Fix PPP file name - Chandan
  docs/AboutUs.md
  docs/team/chandan8186.md
Labels: type.Task

#58 Update About Us and individual PPP - Tim
  docs/AboutUs.md
  docs/images/timleow.png
  docs/team/timleow.md
Labels: priority.High

#76 Update TaskHub Website
  docs/_config.yml
Labels: type.Task

#73 Add Skeletal PPP and About Us - Aslam
  docs/AboutUs.md
  docs/images/aslam341.png
  docs/team/aslam341.md
Labels: type.Task

#63 Update Developer Guide and User Guide - Tim
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/circledHelpGUI.png
  docs/img.png
Labels: type.Task

#71 Add findE and listP commands to User Guide
  docs/UserGuide.md
  docs/images/findEjamesresult.png
  docs/images/listp.png
Labels: type.Task

#80 Add addE and deleteE commands to User Guide
  docs/UserGuide.md
Labels: type.Task

#81 Update commands in Quick Start of UG
  docs/UserGuide.md
Labels: type.Task

#82 Add user stories to Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#36 Add Remark Command - Chandan
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/employee/Employee.java
  src/main/java/seedu/address/model/employee/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEmployee.java
  src/main/java/seedu/address/ui/EmployeeCard.java
  src/main/resources/view/EmployeeListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateEmployeeAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalEmployeesAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/employee/EmployeeTest.java
  src/test/java/seedu/address/model/employee/RemarkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEmployeeTest.java
  src/test/java/seedu/address/testutil/EmployeeBuilder.java
  src/test/java/seedu/address/testutil/EmployeeUtil.java
  src/test/java/seedu/address/testutil/TypicalEmployees.java
Labels: priority.High, type.Task

#89 Add placeholder UI panel frame for projects
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProjectListCard.fxml
  src/main/resources/view/ProjectListPanel.fxml
  src/test/java/seedu/address/model/TaskHubTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/employee/AddressTest.java
  src/test/java/seedu/address/model/employee/EmailTest.java
  src/test/java/seedu/address/model/employee/NameTest.java
  src/test/java/seedu/address/model/employee/PhoneTest.java
  src/test/java/seedu/address/model/employee/RemarkTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: priority.High, type.Task

#98 Refactor add command to addE for employees
  src/main/java/seedu/address/logic/commands/AddEmployeeCommand.java
  src/main/java/seedu/address/logic/parser/AddEmployeeCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddEmployeeCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddEmployeeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEmployeeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/testutil/EmployeeUtil.java
Labels: priority.High

#92 Implement help command and user guide fixes.
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High, type.Task

#106 Implement AssignE
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddProjectCommand.java
  src/main/java/seedu/address/logic/commands/AssignEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddEmployeeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignEmployeeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskHub.java
  src/main/java/seedu/address/model/TaskHub.java
  src/main/java/seedu/address/model/employee/Employee.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/main/java/seedu/address/model/project/exceptions/DuplicateProjectException.java
  src/main/java/seedu/address/model/project/exceptions/ProjectNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEmployee.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonSerializableTaskHub.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/ProjectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AssignEmployeeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/TaskHubTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/model/project/UniqueProjectListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/storage/JsonSerializableTaskHubTest.java
  src/test/java/seedu/address/storage/JsonTaskHubStorageTest.java
  src/test/java/seedu/address/testutil/EmployeeBuilder.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/TypicalEmployees.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: priority.High, type.Task

#108 Implement and modify findP and findE commands
  docs/team/chandan8186.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/FindProjectCommand.java
  src/main/java/seedu/address/logic/parser/FindEmployeeCommandParser.java
  src/main/java/seedu/address/logic/parser/FindProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/main/java/seedu/address/model/employee/EmployeeNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/employee/EmployeeUnderFilteredProjectsPredicate.java
  src/main/java/seedu/address/model/project/ProjectDoneByFilteredEmployeesPredicate.java
  src/main/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindProjectCommandTest.java
  src/test/java/seedu/address/logic/parser/FindEmployeeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/employee/EmployeeNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/employee/EmployeeUnderFilteredProjectsPredicateTest.java
  src/test/java/seedu/address/model/project/ProjectDoneByFilteredEmployeesPredicateTest.java
  src/test/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalEmployees.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: priority.High, type.Task

#109 Edit deadlines for projects
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/ProjectDeadlineCommand.java
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProjectDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/main/java/seedu/address/model/project/Deadline.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/resources/view/ProjectListCard.fxml
  src/test/data/JsonSerializableTaskHubTest/typicalProjectsTaskHub.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ProjectDeadlineCommandTest.java
  src/test/java/seedu/address/logic/parser/ProjectDeadlineCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/model/project/DeadlineTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/testutil/EmployeeBuilder.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: priority.Medium

#110 Implement list command
  docs/UserGuide.md
  docs/images/findEjamesresult.png
  docs/images/findPpresentationresult.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ListEmployeeAndProjectCommand.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListEmployeeAndProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/ListProjectCommandTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
Labels: priority.Medium

#113 Implement priorityP command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/PriorityProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PriorityProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/ProjectPriority.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/resources/view/ProjectListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PriorityProjectCommandTest.java
  src/test/java/seedu/address/logic/parser/PriorityProjectCommandParserTest.java
  src/test/java/seedu/address/model/project/ProjectPriorityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: priority.High

#117 Fix bug where project priority and deadline are not stored simultaneously
  src/main/java/seedu/address/logic/commands/AssignEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/PriorityProjectCommand.java
  src/main/java/seedu/address/logic/commands/ProjectDeadlineCommand.java
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/model/project/Project.java
  src/test/java/seedu/address/logic/commands/PriorityProjectCommandTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
Labels: priority.High

#119 Enable java assertions in gradle
  build.gradle
Labels: priority.High

#130 Update Developer Guide with implementation of MarkP command
  docs/DeveloperGuide.md
  docs/diagrams/MarkPSequenceDiagram.puml
  docs/diagrams/PriorityPSequenceDiagram.puml
  docs/images/MarkPSequenceDiagram.png
  docs/images/PriorityPSequenceDiagram.png
Labels: type.Task

#131 Update Developer Guide with findP command feature
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#137 Add mark and unmark project commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/MarkProjectCommand.java
  src/main/java/seedu/address/logic/commands/PriorityProjectCommand.java
  src/main/java/seedu/address/logic/commands/ProjectDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/main/java/seedu/address/logic/parser/UnmarkProjectCommandParser.java
  src/main/java/seedu/address/model/project/CompletionStatus.java
  src/main/java/seedu/address/model/project/Deadline.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/resources/view/ProjectListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MarkProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/PriorityProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkProjectCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkProjectCommandParserTest.java
  src/test/java/seedu/address/model/project/CompletionStatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: priority.High

#134 Update findP sequence diagram and Model Component in DG
  docs/DeveloperGuide.md
  docs/diagrams/EmployeeClassDiagram.puml
  docs/diagrams/FindPSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ProjectClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/EmployeeClassDiagram.png
  docs/images/FindPSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ProjectClassDiagram.png
Labels: priority.High, type.Task

#140 Update AddProjectCommand and AssignEmployeeCommand to use new method in ParserUtil
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignEmployeeCommandParser.java
Labels: priority.Medium

#142 Refactor Employee to not store Projects
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddProjectCommand.java
  src/main/java/seedu/address/logic/commands/AssignEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteProjectCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddEmployeeCommandParser.java
  src/main/java/seedu/address/model/employee/Employee.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEmployee.java
  src/test/java/seedu/address/model/employee/EmployeeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEmployeeTest.java
  src/test/java/seedu/address/testutil/EmployeeBuilder.java
  src/test/java/seedu/address/testutil/EmployeeUtil.java
  src/test/java/seedu/address/testutil/TypicalEmployees.java
Labels: type.Task

#143 Implement markT and unmarkT commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/main/java/seedu/address/logic/parser/UnmarkTaskCommandParser.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/resources/view/EmployeeListCard.fxml
  src/main/resources/view/ProjectListCard.fxml
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/ModelStubWithProjectAndEmployee.java
Labels: priority.High

#151 Add unassignP command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignProjectCommand.java
  src/main/java/seedu/address/logic/commands/UnassignProjectCommand.java
  src/main/java/seedu/address/logic/parser/AssignProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskHubParser.java
  src/main/java/seedu/address/logic/parser/UnassignProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkProjectCommandParser.java
  src/main/java/seedu/address/model/employee/UniqueEmployeeList.java
  src/test/java/seedu/address/logic/commands/AssignProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignProjectCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TaskHubParserTest.java
  src/test/java/seedu/address/logic/parser/UnassignProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkProjectCommandParserTest.java
Labels: priority.High, type.Task
